pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    blogPostThumb:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 414
                                    height: 227
                                    positioning: center
                                    forceResize: true
                        medias: {  }
                        name: blogPostThumb
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1666971498
                        creationDate: 1666971475
                        preserveAnimation: false
